name: mocap-gs
channels:
  - defaults
dependencies:
  - python=3.10 
  - pip
  - pip:
      - numpy
      - opencv-python
      - matplotlib
      - scipy
      - ids_peak
      - torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu # Adjust based on your system
